apiVersion: v1
kind: Service
metadata:
  name: nginx-app-service
  labels:
    app: nginx-app
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80       
    protocol: TCP
  selector:
    app: nginx-app
